Commit carla_sensors_integration cpp package
usdot-fhwa-stol/carma-carla-integration pull request #3
Opened 2022-08-03 12:46 UTC by lewisid

2022-08-03 21:14 UTC, kjrush requested changes

2022-08-03 21:14 UTC, kjrush commented on carla_sensors_integration/src/carla_sensors_integration.cpp
> +            exit(0);
0 is normally a success exit code, should this be exit(-1)? Or perhaps better, this could be an exception of some sort which might have handlers in the CarmaNodeHandle implementation to cleanly trigger a shutdown (I think).

2022-08-03 21:14 UTC, kjrush commented on carla_sensors_integration/src/carla_sensors_integration.cpp
> +        point_cloud_msg.fields = point_cloud.fields;
Does CARMA Platform use the same fields as the CARLA sensor simulation? It'd be good to check if you're able to compare a ROSbag from the physical vehicle with a ROSBag recorded from CARLA.

2022-08-03 21:14 UTC, kjrush commented on carla_sensors_integration/src/carla_sensors_integration.cpp
> +            ROS_ERROR_STREAM("Invalid image");
In this and the function below, it probably makes sense to either a throw an exception (as mentioned above) if it's an unrecoverable error, or to simply return from the callback if we expect that the next message might be better formed. I think we're probably in the latter case here, but you might know more about why we'd get a 0 size image.

2022-08-03 21:14 UTC, kjrush commented on carla_sensors_integration/src/carla_sensors_integration.cpp
> +        image_raw_sub_ = nh_.subscribe<sensor_msgs::Image>("/carla/{}/camera/image", 10, CarlaSensors::image_raw_cb);
You'll want to have the `{}` replace with a parameter loaded in I think. That's used in Python for string substitution but it's supposed to be replaced with the role name for the specific ego vehicle. In this case simply loading a parameter from the yaml file and concatenating `"/carla/" + config.ego_vehicle_role + "/camera/image"` should work fine.

2022-08-03 21:14 UTC, kjrush commented on carla_sensors_integration/src/carla_sensors_integration.cpp
> +    CarlaSensors::CarlaSensors()
If there's nothing to be done in the constructor, you can just omit it.

2022-08-03 21:14 UTC, kjrush commented on carla_sensors_integration/src/carla_sensors_integration.cpp
> +    void CarlaSensors::initialize()
Where is this called from? Are we missing a main() function for this node?

2022-08-03 21:14 UTC, kjrush commented on carla_sensors_integration/src/carla_sensors_integration.cpp
> +    void CarlaSensors::spin()
Is this supposed to be spinning, or should main call spin on the node handle?

2022-08-10 17:10 UTC, kjrush commented on carla_sensors_integration/include/carla_sensors_integration.h
> +            //ros::CARMANodeHandle nh_;
Is there a particular reason for using the default ROS NodeHandle instead of the CARMA one? Not a dealbreaker, just curious.

2022-08-10 17:10 UTC, kjrush approved these changes

2022-08-10 17:16 UTC, lewisid commented on carla_sensors_integration/include/carla_sensors_integration.h
> +            //ros::CARMANodeHandle nh_;
When I tried running it as a ros::CARMANodeHandle, it would display an error message when trying to use the publisher and subscriber methods in the cpp file.

2022-08-31 20:41 UTC, kjrush approved these changes

2022-08-31 20:41 UTC, merged