Add wait for CARLA functionality
usdot-fhwa-stol/carma-carla-integration pull request #67
Opened 2023-12-26 23:37 UTC by paulbourelly999

# PR Details
## Description

Added script to wait for CARLA. This script can replace sleep commands that were environment specific.

## Related GitHub Issue

## Related Jira Key

## Motivation and Context
[CDAR-632](https://usdot-carma.atlassian.net/browse/CDAR-632)

## How Has This Been Tested?
CDA Sim deployment Integration tested

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-12-27 16:30 UTC, MishkaMN requested changes

2023-12-28 15:23 UTC, paulbourelly999 commented on carma-carla-integration/carla-health-poll/src/wait_for_carla.py
> +        logging.info("Attempting to connect to CARLA at 172.2.0.2:2000")
Addressed

2023-12-28 15:56 UTC, MishkaMN requested changes

2023-12-28 15:56 UTC, MishkaMN commented on carma-carla-integration/carla-health-poll/src/wait_for_carla.py
> +arg_parser = argparse.ArgumentParser(description=__doc__)
if I understand correctly, __doc__ will need description in the python here like aside from the README. Something like this?

"""
This script tries to connect to a CARLA server indefinitely every carla-timeout seconds and exits only when successful. It is used to call before any commands that rely on CARLA's server to be up and communicable.  

Usage:
    python wait_for_carla.py --carla-host <host> --carla-port <port> --carla-timeout <timeout_sec>
"""

2023-12-28 17:15 UTC, paulbourelly999 commented on carma-carla-integration/carla-health-poll/src/wait_for_carla.py
> +arg_parser = argparse.ArgumentParser(description=__doc__)
Adressed

2023-12-28 17:18 UTC, MishkaMN approved these changes

2023-12-28 17:18 UTC, merged