Sync develop to master
usdot-fhwa-stol/carma-carla-integration pull request #76
Opened 2024-04-24 18:18 UTC by paulbourelly999

# PR Details
## Description
This is an intermediate branch cut from master which includes fixes to the branch coupling of build and checkout scripts. This coupling can not yet be removed from CI processes because this repository still uses CircleCI. The functionality to decouple CI from branches is currently only available through our GitHub actions

## Related GitHub Issue

## Related Jira Key

## Motivation and Context
Decouple build/checkout from branch to make release process simpler

## How Has This Been Tested?
CI

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-04-24 18:34 UTC, MishkaMN requested changes

2024-04-24 18:34 UTC, MishkaMN commented on Dockerfile
> +ARG CARMA_VERSION="carma-system-4.5.0"
version needs to be develop

2024-04-24 18:34 UTC, MishkaMN commented on docker/checkout.sh
> +      git clone  https://github.com/usdot-fhwa-stol/autoware.ai.git "${dir}"/src/autoware.ai --branch "${BRANCH}" --depth 1
I am assuming you are taking out the checkout scripts from the instal..sh to here? 
Just to be safe, I would make the directories same as original:
https://github.com/usdot-fhwa-stol/carma-carla-integration/blob/master/docker/install.sh#L32-L49

2024-04-24 18:36 UTC, MishkaMN commented on Dockerfile
> +ARG CARMA_VERSION="carma-system-4.5.0"
if we move the clone lines from install.sh to checkout.sh then we don't even need this ARG

2024-04-24 18:37 UTC, paulbourelly999 commented on Dockerfile
> +ARG CARMA_VERSION="carma-system-4.5.0"
This argument is not used anywhere so I am removing it.

2024-04-24 18:39 UTC, paulbourelly999 commented on docker/checkout.sh
> +      git clone  https://github.com/usdot-fhwa-stol/autoware.ai.git "${dir}"/src/autoware.ai --branch "${BRANCH}" --depth 1
No the directories in the install are hardcoded. This is a bug I have documented here, but I am not able to confidently fix in this PR. (https://usdot-carma.atlassian.net/browse/SIM-5).

2024-04-24 18:44 UTC, MishkaMN commented on docker/checkout.sh
> +      git clone  https://github.com/usdot-fhwa-stol/autoware.ai.git "${dir}"/src/autoware.ai --branch "${BRANCH}" --depth 1
"CARMA_VERSION" ARG is used in the install.sh and acts same function as GIT_BRANCH. Please see the link above. You can replace CARMA_VERSION with GIT_BRANCH however.

2024-04-24 18:45 UTC, MishkaMN requested changes

2024-04-24 18:45 UTC, MishkaMN commented on docker/checkout.sh
> +      git clone  https://github.com/usdot-fhwa-stol/autoware.ai.git "${dir}"/src/autoware.ai --branch "${BRANCH}" --depth 1
Also if you are not fixing install.sh here, then let's remove autoware.ai mention here as it wasn't there on master originally.

2024-04-24 18:46 UTC, MishkaMN requested changes

2024-04-24 18:46 UTC, MishkaMN commented on Dockerfile
> +ARG CARMA_VERSION="carma-system-4.5.0"
"CARMA_VERSION" ARG is used in the install.sh and acts same function as GIT_BRANCH. Please see the link above. You can replace CARMA_VERSION with GIT_BRANCH however.

2024-04-24 18:53 UTC, paulbourelly999 commented on Dockerfile
> +ARG CARMA_VERSION="carma-system-4.5.0"
Hey Misheel, saw your comment on my PR. Currently as far as I can tell the CARMA-VERSION is a build arg that is thrown away at build time during the docker build. There is an environment variable called CARMA-VERSION in the install.sh but as far as I can tell nothing in the docker file or the install.sh script sets this variable so at build time it is empty which is why I removed it.

2024-04-24 18:54 UTC, paulbourelly999 commented on docker/checkout.sh
> +      git clone  https://github.com/usdot-fhwa-stol/autoware.ai.git "${dir}"/src/autoware.ai --branch "${BRANCH}" --depth 1
To use this script in the CI I need to update it here. I can chose to fix nothing or I can chose to fix some of this. Not sure I understand any concern with fixing this file since it is obviously not correct and does not impact anything currently because it is never called.

2024-04-24 19:02 UTC, MishkaMN requested changes

2024-04-24 19:02 UTC, MishkaMN commented on docker/checkout.sh
> +      git clone  https://github.com/usdot-fhwa-stol/autoware.ai.git "${dir}"/src/autoware.ai --branch "${BRANCH}" --depth 1
I am okay you are fixing this. I am just pointing out autoware.ai is extra dependency you are introducing. or am I missing something?

2024-04-24 19:02 UTC, MishkaMN commented on Dockerfile
> +ARG CARMA_VERSION="carma-system-4.5.0"
Is it really correct that we are throwing this away? 
CARMA_VERSION ARG is in the Dockerfile and is used in the install.sh. 
it wouldn't build without it

2024-04-24 19:24 UTC, paulbourelly999 commented on Dockerfile
> +ARG CARMA_VERSION="carma-system-4.5.0"
It is a argument to the dockerfile which means it is only available inside the dockerfile. If we called 
```Dockerfile
RUN install.sh -v ${CARMA-VERSION}
```
or 
```Dockerfile
ENV CARMA-VERSION ${CARMA-VERSION}
```
then it would be available but without that it is not available.

2024-04-24 19:26 UTC, paulbourelly999 commented on docker/checkout.sh
> +      git clone  https://github.com/usdot-fhwa-stol/autoware.ai.git "${dir}"/src/autoware.ai --branch "${BRANCH}" --depth 1
Yeah autoware.ai is a dependency that already exists (see install.sh) it was just included in the incorrect file. I am adding it to the correct file without removing it from the incorrect file because that will likely require more effort than I have time for.

2024-04-24 19:27 UTC, paulbourelly999 commented on Dockerfile
> +ARG CARMA_VERSION="carma-system-4.5.0"
https://docs.docker.com/reference/dockerfile/#arg

https://docs.docker.com/reference/dockerfile/#env

2024-04-24 19:43 UTC, paulbourelly999 commented on Dockerfile
> +ARG CARMA_VERSION="carma-system-4.5.0"
Something in the Docker build does seem to be failing (https://github.com/usdot-fhwa-stol/carma-carla-integration/actions/runs/8822143848/job/24219619855).  This may be related. To be clear, from Docker documentation and from online posts using a Docker ARG outside of the dockerfile without using the ENV instruction seems to be incorrect practice https://vsupalov.com/docker-build-pass-environment-variables/#:~:text=To%20set%20environment%20variables%20during,build%20with%20%2D%2Dbuild%2Darg%20. https://stackoverflow.com/questions/74067493/access-argument-from-docker-build-inside-script. 

I think this just happens to work which is why this was never caught but ARGs are only intended for use inside the dockerfile. I will make an update to see if that fixes the issue.

2024-04-24 20:41 UTC, MishkaMN commented on Dockerfile
> +ARG CARMA_VERSION="carma-system-4.5.0"
Yeah I definitely agree it was an incorrect practice as I got confused first too why that ARG was there when seeimingly it was not used.

2024-04-24 20:42 UTC, MishkaMN commented on docker/checkout.sh
> +      git clone  https://github.com/usdot-fhwa-stol/autoware.ai.git "${dir}"/src/autoware.ai --branch "${BRANCH}" --depth 1
Ah sorry, I overlooked the part where you needed it it here to use this script in the CI. We can fix it in a separate PR.

2024-04-24 20:55 UTC, MishkaMN requested changes

2024-04-24 20:55 UTC, MishkaMN commented on .sonarqube/sonar-scanner.properties
> +carma-carla-bridge.sonar.tests = test
CI is failing because of `test` folder doesn't exist for:
carma-carla-bridge,
carma-carla-agent,
carla-heath-poll
It seems to fail even if we indicate to exclude because the folder doesn't exist. Otherwise looks good so far

2024-04-24 22:02 UTC, MishkaMN approved these changes

2024-04-25 15:03 UTC, kjrush approved these changes

2024-04-29 14:40 UTC, merged